const person[
    { key:1,
        name: 'Shreya Ghoshal',
        income:700000 ,
        born:'Rawatbhata, Rajasthan',
        awards:'Six Filmfare Awards',
        singing:'Classical Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Shreya-Ghoshal.jpg'
     },
    { key:2,
        name: 'Neha Kakkar',
        income:500000 ,
        born:'Uttarakhand',
        awards:' Zee Cine Award',
        singing:'Pop Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Neha-Kakkar-577x577.jpg'
     },
    { key:3,
        name: 'Ankit Tiwari',
        income:1500000 ,
        born:'Kanpur',
        awards:'Filmfare Awards',
        singing:'Sad romantic',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/ankit-tiwwari.jpg'
     },
    { key:4,
        name: 'Sonu Nigam',
        income:400000 ,
        born:'Faridabad, Haryana',
        awards:'Twenty  Filmfare Awards',
        singing:'Filmi music Classical Music',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Sonu-Nigam-577x577.jpg'
     },
    { key:5,
        name: 'Sunidhi Chauhan',
        income:1100000 ,
        born:'New Delhi',
        awards:'Seven Filmfare Awards',
        singing:'Rock Hip hop Sufi Jazz Blues',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Sunidhi-Chauhan-577x704.jpg'
     },
    { key:6,
        name: 'Shankar Mahadevan',
        income:4000000 ,
        born:'Chembur, Mumbai',
        awards:'21 Awards',
        singing:'Hindustani classical Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Shankar-Mahadevan-577x577.jpg'
     },
    { key:7,
        name: 'Arijit Singh',
        income:1300000 ,
        born:'Murshidabad, West Bengal',
        awards:'Twenty Eight Awards',
        singing:'Filmi Sufi Western classical ',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/arijit-singh-577x577.jpg'
     },
    { key:8,
        name: 'Monali Thakur',
        income:800000 ,
        born:'Kolkata',
        awards:'Three Filmfare Awards',
        singing:'Classical Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Monali-Thakur.jpg'
     },
    { key:9,
        name: 'Shaan',
        income:1200000 ,
        born:'Madhya Pradesh',
        awards:'Twelve Filmfare Awards',
        singing:'Pop  Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Shaan-577x577.jpg'
     },
    { key:10,
        name: 'Armaan Malik',
        income:1000000 ,
        born:'Mumbai',
        awards:'BIG Star Entertainment Award',
        singing:'Pop Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Armaan-Malik-577x578.jpg'
     },
    { key:11,
        name: 'Alka Yagnik',
        income:800000 ,
        born:'West Bengal',
        awards:'seven-time  Filmfare',
        singing:'Semiclassical, romantic',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Alka-Yagnik-577x540.jpg'
     },
    { key:12,
        name: 'Amit Trivedi',
        income:600000 ,
        born:'Bandra, Mumbai',
        awards:'Zee Cine Awards',
        singing:'Folk-fusion Song',
        img:'https://www.reviewsxp.com/blog/wp-content/uploads/2019/09/Amit-Trivedi-577x576.jpg'
     },

]